/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;
import java.awt.event.*;

/**
 *
 * @author Gabriel
 */
public class JuegoGato extends javax.swing.JFrame implements ActionListener {
    int contador;
    int jugar;
    private Matriz[][] gato;
    
    /**
     * Creates new form JuegoGato
     */
    public JuegoGato() {
        initComponents();
        NuevoJuego();
    }
    
    public void NuevoJuego() {
        initComponents();

        gato = new Matriz[3][3];
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {

                gato[i][j] = new Matriz();
                gato[i][j].A.setBounds((i * 100) + 22, (j * 100) + 55, 100, 100);
                gato[i][j].A.addActionListener(this);
                this.add(gato[i][j].A);
            }

        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        juegoNuevo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        juegoNuevo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        juegoNuevo.setText("Juego Nuevo");
        juegoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoNuevoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 0, 11)); // NOI18N
        jLabel1.setText("GATO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(juegoNuevo)
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(juegoNuevo)
                    .addComponent(jLabel1))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void juegoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoNuevoActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                
                this.remove(gato[i][j].A); 
                               
            }
        }
        jugar = 0;
        contador = 0;
        this.NuevoJuego();
        jugar = 1;
    }//GEN-LAST:event_juegoNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JuegoGato().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton juegoNuevo;
    // End of variables declaration//GEN-END:variables

    void Turnos(Matriz M) {

        if (contador % 2 == 0) {
            
            M.A.setText("O");
            M.B = 1;
        } else {
            M.A.setText("X");
            M.B = 2;
            
        }
        M.A.removeActionListener(this);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        
        if(jugar == 1){
            for (int i = 0; i < 3; i++) {
                for (int j = 0; j < 3; j++) {
                    
                    if (e.getSource() == gato[i][j].A) {
                        
                        Turnos(gato[i][j]);
                        contador++;
                    }   
                } 
            }    
        }        
    }
    
   
}
